// Generated by pnpm db:types from PostgreSQL migrations. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
"ai_runs": {
Row: {
"id": string;
"organization_id": string;
"actor_id": string;
"entity_id": string;
"feature": string;
"model": string;
"prompt_version": string;
"duration_ms": number;
"tokens": number;
"status": string;
"correlation_id": string;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"actor_id": string;
"entity_id": string;
"feature": string;
"model": string;
"prompt_version": string;
"duration_ms": number;
"tokens"?: number;
"status": string;
"correlation_id"?: string;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"actor_id"?: string;
"entity_id"?: string;
"feature"?: string;
"model"?: string;
"prompt_version"?: string;
"duration_ms"?: number;
"tokens"?: number;
"status"?: string;
"correlation_id"?: string;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"ai_runs_actor_id_fkey";columns:["actor_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"ai_runs_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"approvals": {
Row: {
"id": string;
"organization_id": string;
"import_id": string;
"requested_by": string;
"decided_by": string;
"decision": string;
"comment": string;
"decided_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"import_id": string;
"requested_by": string;
"decided_by": string;
"decision": string;
"comment"?: string;
"decided_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"import_id"?: string;
"requested_by"?: string;
"decided_by"?: string;
"decision"?: string;
"comment"?: string;
"decided_at"?: string;
};
Relationships: [{foreignKeyName:"approvals_decided_by_fkey";columns:["decided_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"approvals_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"approvals_organization_id_import_id_fkey";columns:["organization_id","import_id"];isOneToOne:false;referencedRelation:"imports";referencedColumns:["organization_id","id"]},{foreignKeyName:"approvals_requested_by_fkey";columns:["requested_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
"audit_logs": {
Row: {
"id": string;
"organization_id": string;
"actor_id": string | null;
"action": string;
"entity_type": string;
"entity_id": string | null;
"metadata": Json;
"correlation_id": string;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"actor_id"?: string | null;
"action": string;
"entity_type": string;
"entity_id"?: string | null;
"metadata"?: Json;
"correlation_id"?: string;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"actor_id"?: string | null;
"action"?: string;
"entity_type"?: string;
"entity_id"?: string | null;
"metadata"?: Json;
"correlation_id"?: string;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"audit_logs_actor_id_fkey";columns:["actor_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"audit_logs_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"clients": {
Row: {
"id": string;
"organization_id": string;
"name": string;
"trade_name": string;
"tax_id": string;
"email": string;
"tax_regime": string;
"archived_at": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"name": string;
"trade_name"?: string;
"tax_id"?: string;
"email"?: string;
"tax_regime"?: string;
"archived_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"name"?: string;
"trade_name"?: string;
"tax_id"?: string;
"email"?: string;
"tax_regime"?: string;
"archived_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"clients_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"competencies": {
Row: {
"id": string;
"organization_id": string;
"client_id": string;
"month": string;
"status": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"client_id": string;
"month": string;
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"client_id"?: string;
"month"?: string;
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"competencies_organization_id_client_id_fkey";columns:["organization_id","client_id"];isOneToOne:false;referencedRelation:"clients";referencedColumns:["organization_id","id"]},{foreignKeyName:"competencies_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"departments": {
Row: {
"id": string;
"organization_id": string;
"name": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"name": string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"name"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"departments_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"document_request_items": {
Row: {
"id": string;
"organization_id": string;
"request_id": string;
"label": string;
"status": string;
"document_id": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"request_id": string;
"label": string;
"status"?: string;
"document_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"request_id"?: string;
"label"?: string;
"status"?: string;
"document_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"document_request_items_organization_id_document_id_fkey";columns:["organization_id","document_id"];isOneToOne:false;referencedRelation:"documents";referencedColumns:["organization_id","id"]},{foreignKeyName:"document_request_items_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"document_request_items_organization_id_request_id_fkey";columns:["organization_id","request_id"];isOneToOne:false;referencedRelation:"document_requests";referencedColumns:["organization_id","id"]}];
};
"document_requests": {
Row: {
"id": string;
"organization_id": string;
"client_id": string;
"title": string;
"competence": string;
"due_date": string | null;
"created_by": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"client_id": string;
"title": string;
"competence": string;
"due_date"?: string | null;
"created_by"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"client_id"?: string;
"title"?: string;
"competence"?: string;
"due_date"?: string | null;
"created_by"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"document_requests_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"document_requests_organization_id_client_id_fkey";columns:["organization_id","client_id"];isOneToOne:false;referencedRelation:"clients";referencedColumns:["organization_id","id"]},{foreignKeyName:"document_requests_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"documents": {
Row: {
"id": string;
"organization_id": string;
"client_id": string;
"competence": string;
"original_filename": string;
"mime_type": string;
"size": number;
"storage_path": string;
"checksum": string;
"uploaded_by": string;
"category": string;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"client_id": string;
"competence": string;
"original_filename": string;
"mime_type": string;
"size": number;
"storage_path": string;
"checksum": string;
"uploaded_by"?: string;
"category"?: string;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"client_id"?: string;
"competence"?: string;
"original_filename"?: string;
"mime_type"?: string;
"size"?: number;
"storage_path"?: string;
"checksum"?: string;
"uploaded_by"?: string;
"category"?: string;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"documents_organization_id_client_id_fkey";columns:["organization_id","client_id"];isOneToOne:false;referencedRelation:"clients";referencedColumns:["organization_id","id"]},{foreignKeyName:"documents_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"documents_uploaded_by_fkey";columns:["uploaded_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
"employee_snapshots": {
Row: {
"id": string;
"organization_id": string;
"client_id": string;
"import_id": string;
"competence": string;
"employee_name": string;
"employee_cpf": string;
"salary": number | null;
"admission_date": string | null;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"client_id": string;
"import_id": string;
"competence": string;
"employee_name": string;
"employee_cpf": string;
"salary"?: number | null;
"admission_date"?: string | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"client_id"?: string;
"import_id"?: string;
"competence"?: string;
"employee_name"?: string;
"employee_cpf"?: string;
"salary"?: number | null;
"admission_date"?: string | null;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"employee_snapshots_organization_id_client_id_fkey";columns:["organization_id","client_id"];isOneToOne:false;referencedRelation:"clients";referencedColumns:["organization_id","id"]},{foreignKeyName:"employee_snapshots_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"employee_snapshots_organization_id_import_id_fkey";columns:["organization_id","import_id"];isOneToOne:false;referencedRelation:"imports";referencedColumns:["organization_id","id"]}];
};
"import_templates": {
Row: {
"id": string;
"organization_id": string;
"name": string;
"headers": Json;
"mapping": Json;
"fingerprint": string;
"source_import_id": string;
"created_by": string;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"name": string;
"headers": Json;
"mapping": Json;
"fingerprint": string;
"source_import_id": string;
"created_by"?: string;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"name"?: string;
"headers"?: Json;
"mapping"?: Json;
"fingerprint"?: string;
"source_import_id"?: string;
"created_by"?: string;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"import_templates_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"import_templates_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"import_templates_organization_id_source_import_id_fkey";columns:["organization_id","source_import_id"];isOneToOne:false;referencedRelation:"imports";referencedColumns:["organization_id","id"]}];
};
"imports": {
Row: {
"id": string;
"organization_id": string;
"client_id": string;
"competence": string;
"original_filename": string;
"storage_path": string;
"checksum": string;
"status": string;
"sheets": Json;
"sheet_index": number;
"header_row": number;
"headers": Json;
"mapping": Json;
"validation": Json | null;
"validated_records": Json | null;
"created_by": string;
"approved_by": string | null;
"approved_at": string | null;
"completed_at": string | null;
"row_count": number;
"version": number;
"correlation_id": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"client_id": string;
"competence": string;
"original_filename": string;
"storage_path": string;
"checksum": string;
"status"?: string;
"sheets": Json;
"sheet_index"?: number;
"header_row"?: number;
"headers"?: Json;
"mapping"?: Json;
"validation"?: Json | null;
"validated_records"?: Json | null;
"created_by"?: string;
"approved_by"?: string | null;
"approved_at"?: string | null;
"completed_at"?: string | null;
"row_count"?: number;
"version"?: number;
"correlation_id"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"client_id"?: string;
"competence"?: string;
"original_filename"?: string;
"storage_path"?: string;
"checksum"?: string;
"status"?: string;
"sheets"?: Json;
"sheet_index"?: number;
"header_row"?: number;
"headers"?: Json;
"mapping"?: Json;
"validation"?: Json | null;
"validated_records"?: Json | null;
"created_by"?: string;
"approved_by"?: string | null;
"approved_at"?: string | null;
"completed_at"?: string | null;
"row_count"?: number;
"version"?: number;
"correlation_id"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"imports_approved_by_fkey";columns:["approved_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"imports_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"imports_organization_id_client_id_fkey";columns:["organization_id","client_id"];isOneToOne:false;referencedRelation:"clients";referencedColumns:["organization_id","id"]},{foreignKeyName:"imports_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"member_roles": {
Row: {
"organization_id": string;
"member_id": string;
"role_id": string;
};
Insert: {
"organization_id": string;
"member_id": string;
"role_id": string;
};
Update: {
"organization_id"?: string;
"member_id"?: string;
"role_id"?: string;
};
Relationships: [{foreignKeyName:"member_roles_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"member_roles_organization_id_member_id_fkey";columns:["organization_id","member_id"];isOneToOne:false;referencedRelation:"organization_members";referencedColumns:["organization_id","id"]},{foreignKeyName:"member_roles_organization_id_role_id_fkey";columns:["organization_id","role_id"];isOneToOne:false;referencedRelation:"roles";referencedColumns:["organization_id","id"]}];
};
"notifications": {
Row: {
"id": string;
"organization_id": string;
"user_id": string;
"kind": string;
"title": string;
"href": string;
"read_at": string | null;
"dedupe_key": string | null;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"user_id": string;
"kind": string;
"title": string;
"href": string;
"read_at"?: string | null;
"dedupe_key"?: string | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"user_id"?: string;
"kind"?: string;
"title"?: string;
"href"?: string;
"read_at"?: string | null;
"dedupe_key"?: string | null;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"notifications_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"notifications_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
"organization_members": {
Row: {
"id": string;
"organization_id": string;
"user_id": string;
"department_id": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"user_id": string;
"department_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"user_id"?: string;
"department_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"organization_members_organization_id_department_id_fkey";columns:["organization_id","department_id"];isOneToOne:false;referencedRelation:"departments";referencedColumns:["organization_id","id"]},{foreignKeyName:"organization_members_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"organization_members_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
"organization_settings": {
Row: {
"id": string;
"organization_id": string;
"ai_enabled": boolean;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"ai_enabled"?: boolean;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"ai_enabled"?: boolean;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"organization_settings_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"organizations": {
Row: {
"id": string;
"name": string;
"created_by": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"name": string;
"created_by": string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"name"?: string;
"created_by"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"organizations_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
"outbox_events": {
Row: {
"id": string;
"organization_id": string;
"kind": string;
"entity_id": string;
"status": string;
"attempt_count": number;
"last_error": string | null;
"scheduled_at": string;
"started_at": string | null;
"completed_at": string | null;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"kind": string;
"entity_id": string;
"status"?: string;
"attempt_count"?: number;
"last_error"?: string | null;
"scheduled_at"?: string;
"started_at"?: string | null;
"completed_at"?: string | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"kind"?: string;
"entity_id"?: string;
"status"?: string;
"attempt_count"?: number;
"last_error"?: string | null;
"scheduled_at"?: string;
"started_at"?: string | null;
"completed_at"?: string | null;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"outbox_events_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"permissions": {
Row: {
"id": string;
};
Insert: {
"id": string;
};
Update: {
"id"?: string;
};
Relationships: [];
};
"profiles": {
Row: {
"id": string;
"full_name": string;
"phone": string;
"job_title": string;
"avatar_path": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id": string;
"full_name"?: string;
"phone"?: string;
"job_title"?: string;
"avatar_path"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"full_name"?: string;
"phone"?: string;
"job_title"?: string;
"avatar_path"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"profiles_id_fkey";columns:["id"];isOneToOne:false;referencedRelation:"users";referencedColumns:["id"]}];
};
"rate_limits": {
Row: {
"id": string;
"organization_id": string;
"user_id": string;
"feature": string;
"window_start": string;
"hits": number;
};
Insert: {
"id"?: string;
"organization_id": string;
"user_id": string;
"feature": string;
"window_start"?: string;
"hits"?: number;
};
Update: {
"id"?: string;
"organization_id"?: string;
"user_id"?: string;
"feature"?: string;
"window_start"?: string;
"hits"?: number;
};
Relationships: [{foreignKeyName:"rate_limits_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"rate_limits_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
"role_permissions": {
Row: {
"organization_id": string;
"role_id": string;
"permission": string;
};
Insert: {
"organization_id": string;
"role_id": string;
"permission": string;
};
Update: {
"organization_id"?: string;
"role_id"?: string;
"permission"?: string;
};
Relationships: [{foreignKeyName:"role_permissions_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"role_permissions_organization_id_role_id_fkey";columns:["organization_id","role_id"];isOneToOne:false;referencedRelation:"roles";referencedColumns:["organization_id","id"]},{foreignKeyName:"role_permissions_permission_fkey";columns:["permission"];isOneToOne:false;referencedRelation:"permissions";referencedColumns:["id"]}];
};
"roles": {
Row: {
"id": string;
"organization_id": string;
"name": string;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"name": string;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"name"?: string;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"roles_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"task_comments": {
Row: {
"id": string;
"organization_id": string;
"task_id": string;
"author_id": string;
"body": string;
"created_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"task_id": string;
"author_id"?: string;
"body": string;
"created_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"task_id"?: string;
"author_id"?: string;
"body"?: string;
"created_at"?: string;
};
Relationships: [{foreignKeyName:"task_comments_author_id_fkey";columns:["author_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"task_comments_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"task_comments_organization_id_task_id_fkey";columns:["organization_id","task_id"];isOneToOne:false;referencedRelation:"tasks";referencedColumns:["organization_id","id"]}];
};
"task_dependencies": {
Row: {
"organization_id": string;
"task_id": string;
"depends_on_id": string;
};
Insert: {
"organization_id": string;
"task_id": string;
"depends_on_id": string;
};
Update: {
"organization_id"?: string;
"task_id"?: string;
"depends_on_id"?: string;
};
Relationships: [{foreignKeyName:"task_dependencies_organization_id_depends_on_id_fkey";columns:["organization_id","depends_on_id"];isOneToOne:false;referencedRelation:"tasks";referencedColumns:["organization_id","id"]},{foreignKeyName:"task_dependencies_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]},{foreignKeyName:"task_dependencies_organization_id_task_id_fkey";columns:["organization_id","task_id"];isOneToOne:false;referencedRelation:"tasks";referencedColumns:["organization_id","id"]}];
};
"tasks": {
Row: {
"id": string;
"organization_id": string;
"client_id": string;
"competence": string;
"title": string;
"description": string;
"status": string;
"priority": string;
"department_id": string | null;
"assignee_id": string | null;
"created_by": string;
"due_date": string | null;
"started_at": string | null;
"completed_at": string | null;
"blocked_reason": string | null;
"version": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"organization_id": string;
"client_id": string;
"competence": string;
"title": string;
"description"?: string;
"status"?: string;
"priority"?: string;
"department_id"?: string | null;
"assignee_id"?: string | null;
"created_by"?: string;
"due_date"?: string | null;
"started_at"?: string | null;
"completed_at"?: string | null;
"blocked_reason"?: string | null;
"version"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"organization_id"?: string;
"client_id"?: string;
"competence"?: string;
"title"?: string;
"description"?: string;
"status"?: string;
"priority"?: string;
"department_id"?: string | null;
"assignee_id"?: string | null;
"created_by"?: string;
"due_date"?: string | null;
"started_at"?: string | null;
"completed_at"?: string | null;
"blocked_reason"?: string | null;
"version"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"tasks_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"tasks_organization_id_assignee_id_fkey";columns:["organization_id","assignee_id"];isOneToOne:false;referencedRelation:"organization_members";referencedColumns:["organization_id","user_id"]},{foreignKeyName:"tasks_organization_id_client_id_fkey";columns:["organization_id","client_id"];isOneToOne:false;referencedRelation:"clients";referencedColumns:["organization_id","id"]},{foreignKeyName:"tasks_organization_id_department_id_fkey";columns:["organization_id","department_id"];isOneToOne:false;referencedRelation:"departments";referencedColumns:["organization_id","id"]},{foreignKeyName:"tasks_organization_id_fkey";columns:["organization_id"];isOneToOne:false;referencedRelation:"organizations";referencedColumns:["id"]}];
};
"user_preferences": {
Row: {
"id": string;
"theme": string;
"density": string;
"sidebar_collapsed": boolean;
"timezone": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id": string;
"theme"?: string;
"density"?: string;
"sidebar_collapsed"?: boolean;
"timezone"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"theme"?: string;
"density"?: string;
"sidebar_collapsed"?: boolean;
"timezone"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{foreignKeyName:"user_preferences_id_fkey";columns:["id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}];
};
}; Views: { [_ in never]: never }; Functions: {
"approve_import": { Args: {"import_id":string;"expected_version":number;"approval_comment"?:string}; Returns: undefined };
"can_access_storage": { Args: {"object_name":string;"operation":string}; Returns: boolean };
"configure_import": { Args: {"import_id":string;"expected_version":number;"selected_sheet":number;"selected_header":number;"selected_mapping":Json}; Returns: number };
"consume_rate_limit": { Args: {"org_id":string;"feature_name":string}; Returns: boolean };
"create_document_request": { Args: {"org_id":string;"target_client":string;"title":string;"competence":string;"labels":string[];"due"?:string}; Returns: string };
"create_import": { Args: {"org_id":string;"target_client":string;"target_competence":string;"filename":string;"path":string;"file_checksum":string;"workbook":Json}; Returns: string };
"create_organization": { Args: {"org_name":string;"person_name":string;"department_names":string[]}; Returns: string };
"create_verified_import": { Args: {"payload":string;"signature":string}; Returns: string };
"emit_due_notifications": { Args: {}; Returns: undefined };
"has_org_permission": { Args: {"org_id":string;"permission":string}; Returns: boolean };
"is_org_member": { Args: {"org_id":string}; Returns: boolean };
"manage_member": { Args: {"org_id":string;"email_address":string;"selected_role":string;"selected_department"?:string}; Returns: undefined };
"process_import": { Args: {"import_id":string}; Returns: number };
"process_pending_imports": { Args: {}; Returns: number };
"save_import_template": { Args: {"import_id":string;"template_name":string}; Returns: string };
"set_task_dependency": { Args: {"task_id":string;"dependency_id":string;"remove_dependency"?:boolean}; Returns: undefined };
"share_organization": { Args: {"other_user":string}; Returns: boolean };
"valid_cpf": { Args: {"value":string}; Returns: boolean };
"validate_import": { Args: {"import_id":string;"expected_version":number}; Returns: Json };
}; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };
export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
