// Generates the Supabase-compatible Database shape from actual PostgreSQL catalog
// metadata. The migrations are executed first, including all constraints and RLS.
import { createDatabase } from './database-harness.mjs';
import { writeFile } from 'node:fs/promises';
const db = await createDatabase();
const mapType = (t) =>
  t.endsWith('[]')
    ? `${mapType(t.slice(0, -2))}[]`
    : ['json', 'jsonb'].includes(t)
      ? 'Json'
      : t === 'record'
        ? 'Json'
      : t === 'boolean'
        ? 'boolean'
        : ['integer', 'bigint', 'smallint', 'numeric', 'double precision', 'real'].includes(t)
          ? 'number'
          : t === 'void'
            ? 'undefined'
            : 'string';
const { rows: tables } = await db.query(
  `select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by table_name`,
);
let output =
  '// Generated by pnpm db:types from PostgreSQL migrations. Do not edit.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type Database = { public: { Tables: {\n';
for (const { table_name: table } of tables) {
  const { rows: cols } = await db.query(
    `select column_name,data_type,is_nullable,column_default,udt_name from information_schema.columns where table_schema='public' and table_name=$1 order by ordinal_position`,
    [table],
  );
  output += `${JSON.stringify(table)}: {\n`;
  for (const operation of ['Row', 'Insert', 'Update']) {
    output += `${operation}: {\n`;
    for (const c of cols)
      output += `${JSON.stringify(c.column_name)}${operation === 'Update' || (operation === 'Insert' && (c.column_default || c.is_nullable === 'YES')) ? '?' : ''}: ${mapType(c.data_type === 'ARRAY' ? c.udt_name.slice(1) + '[]' : c.data_type)}${c.is_nullable === 'YES' ? ' | null' : ''};\n`;
    output += '};\n';
  }
  const { rows: fks } = await db.query(
    `select c.conname, array(select a.attname from unnest(c.conkey) with ordinality k(attnum,ord) join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.attnum order by ord) as columns, r.relname as referenced_relation, array(select a.attname from unnest(c.confkey) with ordinality k(attnum,ord) join pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.attnum order by ord) as referenced_columns from pg_constraint c join pg_class r on r.oid=c.confrelid where c.contype='f' and c.conrelid=('public.'||$1)::regclass`,
    [table],
  );
  output += `Relationships: [${fks.map((f) => `{foreignKeyName:${JSON.stringify(f.conname)};columns:${JSON.stringify(f.columns)};isOneToOne:false;referencedRelation:${JSON.stringify(f.referenced_relation)};referencedColumns:${JSON.stringify(f.referenced_columns)}}`).join(',')}];\n};\n`;
}
output += '}; Views: { [_ in never]: never }; Functions: {\n';
const { rows: funcs } = await db.query(
  `select p.proname,p.proargnames,array(select format_type(t,null) from unnest(p.proargtypes::oid[]) t) types,format_type(p.prorettype,null) result,p.pronargdefaults from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prorettype<>'trigger'::regtype order by p.proname`,
);
for (const f of funcs) {
  const inputNames = (f.proargnames ?? []).slice(0, f.types.length);
  output += `${JSON.stringify(f.proname)}: { Args: {${inputNames.map((name, i) => `${JSON.stringify(name)}${i >= f.types.length - f.pronargdefaults ? '?' : ''}:${mapType(f.types[i])}`).join(';')}}; Returns: ${mapType(f.result)} };\n`;
}
output +=
  '}; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };\nexport type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];\n';
await writeFile('packages/types/src/database.ts', output);
await db.close();
console.log(
  `Generated types for ${tables.length} tables and ${funcs.length} functions; migrations applied successfully.`,
);
